language: java
jdk:
- oraclejdk8
before_install: 
- cd Budget/demo
- chmod +x mvnw
notifications:
  email:
    - krzysztof.stengert@hotmail.com
    - johnnybe.beczcki@gmail.com
    - MaverickCCCP@gmail.com