language: java
jdk:
- oraclejdk8
services:
    -mysql
dist: trusty
sudo: required
before_install: 
- cd Budget/demo
- chmod +x mvnw
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- mysql -u root -e "create database budgetdb;"
- mysql -u root -e "create user budget@localhost identified by 'koziadupa123';"
- mysql -u root -e "grant all on budgetdb.* to budget@localhost;"
notifications:
  email:
    - krzysztof.stengert@hotmail.com
    - johnnybe.beczcki@gmail.com
    - MaverickCCCP@gmail.com